server:
  port: 80
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/evos_bot
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 15MB